version: '3.8'

services:
  yusi-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: yusi-front:latest
    container_name: yusi-front
    restart: always
    ports:
      - "8080:8080"
    environment:
      # 高德地图 JS API Key（运行时注入）
      - AMAP_JS_KEY=${AMAP_JS_KEY}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge
    external: true
